name: "Alba Security"
description: "Alba Security accesible desde: http://homeassistant.local:5173/"
version: "4.0"
slug: "alba_security"
init: false
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386
startup: services
ingress: false
panel_icon: "mdi:shield-lock" 
panel_title: "Alba Security"

map: ["data"]

host_network: true

options: 
  token_ha:         # Perfil -> Seguridad -> Tokens de acceso de larga duraci√≥n
  api_key_abuse:    # Clave para api de AbuseIPDB
  url:              # Home Assistant Url

ports:
  5173/tcp: 5173
  8000/tcp: 8000
